#pragma once

void int_0_handler();
void int_1_handler();
void int_2_handler();
void int_3_handler();
void int_4_handler();
void int_5_handler();
void int_6_handler();
void int_7_handler();
void int_8_handler();
void int_9_handler();
void int_10_handler();
void int_11_handler();
void int_12_handler();
void int_13_handler();
void int_14_handler();
void int_15_handler();
void int_16_handler();
void int_17_handler();
void int_18_handler();
void int_19_handler();
void int_20_handler();
void int_21_handler();
void int_22_handler();
void int_23_handler();
void int_24_handler();
void int_25_handler();
void int_26_handler();
void int_27_handler();
void int_28_handler();
void int_29_handler();
void int_30_handler();
void int_31_handler();
/*
void irq_0_handler();
void irq_1_handler();
void irq_2_handler();
void irq_3_handler();
void irq_4_handler();
void irq_5_handler();
void irq_6_handler();
void irq_7_handler();
void irq_8_handler();
void irq_9_handler();
void irq_10_handler();
void irq_11_handler();
void irq_12_handler();
void irq_13_handler();
void irq_14_handler();
void irq_15_handler();*/

void irq_handler();